<?php $_config_vars = array (
  'SeperatorLine' => '#5B0000',
  'DynamicBG' => '#CFCECD',
  'TR_ODD_COLOR' => '#ffffff',
  'TR_EVEN_COLOR' => '#e7e7e7',
  'BODY_BGCOLOR' => '#ffffff',
  'TR_MOUSEOVER_COLOR' => '#e8f0fe',
  'TABLE_BG_COLOR' => '#383535',
  'TABLE_BG_COLOR1' => '#EFEFEF',
  'TABLE_BG_COLOR2' => '#B0B0B0',
  'TABLE_BG_COLOR3' => 'red',
  'TABLE_HEAD_BGRD' => 'background="images_yellow/resource_bg.gif"',
  'TABLE_HEAD_BGRDg' => 'background="images_yellow/resource_bg1.gif"',
  'TABLE_HEAD_BGRD1' => 'background="images_yellow/resource_ubg.gif"',
  'TABLE_HEAD_BGRD1G' => 'background="images_yellow/resource_ubg1.gif"',
  'TABLE_LINE_BG' => 'background="images_yellow/line_bg.gif"',
  'TABLE_HEAD_BGRes' => 'background="images_yellow/resources_bg.gif"',
  'TABLE_HEAD_BGResAdd' => 'background="images_yellow/resources_add_bg.gif"',
  'TABLE_HEAD_BG32' => 'background="images_yellow/bg32.gif" height="32"',
  'TABLE_HEAD_BG38' => 'background="images_yellow/bg38.gif"',
  'TABLE_HEAD_BG38d' => 'background="images_yellow/bg38d.gif"',
  'TABLE_HEAD_BG51' => 'background="images_yellow/bill51.gif"',
  'TABLE_HEAD_BG51d' => 'background="images_yellow/bg51d.gif"',
  'BILL32' => 'background="images_yellow/bill32.gif"',
  'LINE_BG1' => '#E9FAD0;',
  'LINE_BG2' => '#E5F6FD;',
  'LINE_BG3' => '#FDE1E1;',
); ?>